---
title: "Probando paquetes"
author: "Santiago Sotelo"
date: '2022-05-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Paquetes

```{r}
pacman::p_load(
  #Working directory
  here,
  #data tools
  tidyverse, janitor, glue, lubridate, scales, Hmisc,lazyeval,
  #Gráficos
  plotly, ggrepel, cowplot, grid,
  #importar / exportar
  haven, rio, officer, officedown,
  #Etiquetas
  sjlabelled,
  #tablas
  xtable, flextable, knitr, kableExtra, DT, gtsummary, gt,
  #Visualización
  ggpubr, paletteer, RColorBrewer, grid, ggthemes, rvg, cowplot,  scales, ggtext, ggrepel,
  #mapas
  sf, sfheaders, leaflet, osmdata,
  #Trabajar con encuestas
  survey, srvyr
  )

#Set working directory de manera relativa
here::i_am("scripts/prueba_paquetes.Rmd")

```

El objetivo de este script es probar el paquete `svyr` y relativos, para una mejor elaboración de las tablas.

## Material de apoyo

http://gdfe.co/srvyr/articles/srvyr-vs-survey.html#motivating-example-1

https://www.danieldsjoberg.com/gtsummary/reference/tbl_svysummary.html

https://medium.com/tacosdedatos/usando-r-para-sacar-informaci%C3%B3n-de-los-microdatos-del-inegi-b21b6946cf4f

## Código Claudio Pacheco

```{r}
#Descarga de archivos
url<-"https://www.inegi.org.mx/contenidos/programas/enigh/nc/2018/microdatos/enigh2018_ns_viviendas_csv.zip"
##Creación de directorio temporal
td<- tempdir()
# Descarga del archivo temporal
tf = tempfile(tmpdir=td, fileext=".zip")
download.file(url, tf)
# unzip
unzip(tf, files="viviendas.csv", exdir=td, 
      overwrite=TRUE)
fpath=file.path(td,"viviendas.csv")
unlink(td)

```

```{r}
#Leer el archivo
enigh<-read.csv(fpath)%>%
  #Renombrar folioviv
  rename(folioviv=1)

```

```{r}
enigh<-enigh%>%
#Obtener la clave de entidad de la variable folioviv
  mutate(cve_ent=
           case_when(nchar(folioviv)==9 ~ substr(folioviv,1,1),
                     TRUE ~substr(folioviv,1,2)),
#Creamos nombre de entidad
                 nom_ent= case_when(cve_ent==1 ~ "Aguascalientes",
                       cve_ent==2 ~ "Baja California",
                       cve_ent==3 ~ "Baja California Sur",
                       cve_ent==4 ~ "Campeche",
                       cve_ent==5 ~ "Coahuila de Zaragoza",
                       cve_ent==6 ~ "Colima",
                       cve_ent==7 ~ "Chiapas",
                       cve_ent==8 ~ "Chihuahua",
                       cve_ent==9 ~ "Ciudad de México",
                       cve_ent==10 ~ "Durango",
                       cve_ent==11 ~ "Guanajuato",
                       cve_ent==12 ~ "Guerrero",
                       cve_ent==13 ~ "Hidalgo",
                       cve_ent==14 ~ "Jalisco",
                       cve_ent==15 ~ "México",
                       cve_ent==16 ~ "Michoacán de Ocampo",
                       cve_ent==17 ~ "Morelos",
                       cve_ent==18 ~ "Nayarit",
                       cve_ent==19 ~ "Nuevo León",
                       cve_ent==20 ~ "Oaxaca",
                       cve_ent==21 ~ "Puebla",
                       cve_ent==22 ~ "Querétaro",
                       cve_ent==23 ~ "Quintana Roo",
                       cve_ent==24 ~ "San Luis Potosí",
                       cve_ent==25 ~ "Sinaloa",
                       cve_ent==26 ~ "Sonora",
                       cve_ent==27 ~ "Tabasco",
                       cve_ent==28 ~ "Tamaulipas",
                       cve_ent==29 ~ "Tlaxcala",
                       cve_ent==30 ~ "Veracruz de Ignacio de la Llave",
                       cve_ent==31 ~ "Yucatán",
                       cve_ent==32 ~ "Zacatecas"))
```

```{r}
enigh<-enigh%>%
#Creamos indicador de hacinamiento
  mutate(hac=case_when((tot_resid / num_cuarto) > 2.5 ~ 1,
                TRUE ~ 0))
```

```{r}
#Definir diseño muestral
mydesign <-enigh%>%
  as_survey_design(ids=upm,
                   strata=est_dis,
                   weights=factor)
```

Como vemos, usamos las UPM (upm), el estrado de diseño (est_dis) y el factor de expansión (factor).

```{r}
#Viviendas con habitantes en condición de hacinamiento nacional
hacnal<-mydesign %>%
  filter(hac==1)%>%
  summarise(hac=survey_total(
    vartype = c("cv", "ci"),
    level=0.95))%>%
  mutate(hac_cv=
           hac_cv*100,
#Formato de números
hac=format(hac,big.mark=","),
hac_cv=round(hac_cv,2),
hac_low=format(hac_low,big.mark=","),
hac_upp=format(hac_upp,big.mark=","),
)
```

Con estos resultados, hacemos una tablita usando KableExtra:

```{r}
#Tabla Nacional
hacnal%>%
kable(caption=text_spec("México. Viviendas con habitantes en condición de hacinamiento, 2018",
                        bold=T, color="black",font_size = 30),
      format="html",
      align = "c",
      col.names = c("Viviendas con  habitantes en condición de\n
                    hacinamiento",
                    "Coeficiente de variación",
                    "Límite inferior",
                    "Límite superior"))%>%
  kable_styling(full_width = F, font_size = 20,
                html_font = "Montserrat Medium")%>%
  row_spec(0, bold = F, color = "black", background = "#9ebcda")%>%
  footnote(general = "@claudiodanielpc con información de INEGI. Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH) 2018",
           general_title = "
Fuente: ")#%>%
  # #Salvar
  # as_image(file="hacnal.png")
```

```{r}
#Viviendas con habitantes en condición de hacinamiento por entidad federativa
hacent<-mydesign %>%
  filter(hac==1)%>%
  group_by(nom_ent)%>%
  summarise(hac=survey_total(
    vartype = c("cv", "ci"),
    level=0.95))%>%
  #Multiplicar coeficiente de variación por 100
  mutate(hac_cv=
           hac_cv*100,
         #Formato de números
         hac=format(hac,big.mark=","),
         hac_cv=round(hac_cv,2),
         hac_low=format(hac_low,big.mark=","),
         hac_upp=format(hac_upp,big.mark=","),
  )
#Tabla por entidad federativa
hacent%>%
  kable(caption=text_spec("Viviendas con habitantes en condición de hacinamiento por entidad federativa, 2018",
                          bold=T, color="black",font_size = 30),
        format="html",
        align = "c",
        col.names = c("Entidad",
        "Viviendas con  habitantes 
en condición de\n
                    hacinamiento",
                      "Coeficiente de variación",
                      "Límite inferior",
                      "Límite superior"))%>%
  kable_styling(full_width = F, font_size = 20,
                html_font = "Montserrat Medium")%>%
  row_spec(0, bold = F, color = "black", background = "#9ebcda")%>%
  footnote(general = "@claudiodanielpc con información de INEGI. Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH) 2018",
           general_title = "
Fuente: ")#%>%
  # #Salvar
  # as_image(file="hacent.png")
```

## gdfe documentación syvr

```{r}
library(srvyr)

data(api)

# simple random sample
srs_design_srvyr <- apisrs %>% as_survey_design(ids = 1, fpc = fpc)

srs_design_survey <- svydesign(ids = ~1, fpc = ~fpc, data = apisrs)
```

```{r}
# selecting variables to keep in the survey object (stratified example)
strat_design_srvyr <- apistrat %>%
  as_survey_design(1, strata = stype, fpc = fpc, weight = pw,
                variables = c(stype, starts_with("api")))

strat_design_survey <- svydesign(~1, strata = ~stype, fpc = ~fpc,
                                 variables = ~stype + api99 + api00 + api.stu,
                                 weight = ~pw, data = apistrat)
```

```{r}
strat_design_srvyr <- strat_design_srvyr %>%
  mutate(api_diff = api00 - api99) %>%
  rename(api_students = api.stu)

strat_design_survey$variables$api_diff <- strat_design_survey$variables$api00 -
  strat_design_survey$variables$api99
names(strat_design_survey$variables)[names(strat_design_survey$variables) == "api.stu"] <- "api_students"
```

